# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SmoothCSV 2
email: smoothcsv@hotmail.co.jp
description: > # this means to ignore newlines until "baseurl:"
  SmoothCSV is a awesome CSV file editor.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://smoothcsv.com" # the base hostname & protocol for your site
#twitter_username: 
#github_username:  kohii

# Build settings
markdown: kramdown

languages: ["en", "ja"]
exclude_from_localizations: ["javascript", "images", "css", "download", "macro_api", "manuals", "v1"]

gems:
  - jekyll-redirect-from
  - jekyll-multiple-languages-plugin
  # - jemoji
  # - jekyll-mentions
  # - jekyll-redirect-from
  # - jekyll-sitemap
  # - jekyll-feed